plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.hujiayucc.notask'
    compileSdk = 37

    defaultConfig {
        applicationId = "com.hujiayucc.notask"
        minSdk = 26
        targetSdk = 37
        versionCode = 12
        versionName = "1.2"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packaging {
        resources {
            merges += 'META-INF/xposed/*'
        }
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
}